// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log.proto

package log

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Level int32

const (
	Level_PANIC Level = 0
	Level_FATAL Level = 1
	Level_ERROR Level = 2
	Level_WARN  Level = 3
	Level_INFO  Level = 4
	Level_DEBUG Level = 5
	Level_TRACE Level = 6
)

var Level_name = map[int32]string{
	0: "PANIC",
	1: "FATAL",
	2: "ERROR",
	3: "WARN",
	4: "INFO",
	5: "DEBUG",
	6: "TRACE",
}

var Level_value = map[string]int32{
	"PANIC": 0,
	"FATAL": 1,
	"ERROR": 2,
	"WARN":  3,
	"INFO":  4,
	"DEBUG": 5,
	"TRACE": 6,
}

func (x Level) String() string {
	return proto.EnumName(Level_name, int32(x))
}

func (Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{0}
}

type SetLevelRequest struct {
	Level                Level    `protobuf:"varint,1,opt,name=level,proto3,enum=log.Level" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetLevelRequest) Reset()         { *m = SetLevelRequest{} }
func (m *SetLevelRequest) String() string { return proto.CompactTextString(m) }
func (*SetLevelRequest) ProtoMessage()    {}
func (*SetLevelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{0}
}

func (m *SetLevelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLevelRequest.Unmarshal(m, b)
}
func (m *SetLevelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLevelRequest.Marshal(b, m, deterministic)
}
func (m *SetLevelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLevelRequest.Merge(m, src)
}
func (m *SetLevelRequest) XXX_Size() int {
	return xxx_messageInfo_SetLevelRequest.Size(m)
}
func (m *SetLevelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLevelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetLevelRequest proto.InternalMessageInfo

func (m *SetLevelRequest) GetLevel() Level {
	if m != nil {
		return m.Level
	}
	return Level_PANIC
}

type SetLevelResponse struct {
	Level                Level    `protobuf:"varint,1,opt,name=level,proto3,enum=log.Level" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetLevelResponse) Reset()         { *m = SetLevelResponse{} }
func (m *SetLevelResponse) String() string { return proto.CompactTextString(m) }
func (*SetLevelResponse) ProtoMessage()    {}
func (*SetLevelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{1}
}

func (m *SetLevelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLevelResponse.Unmarshal(m, b)
}
func (m *SetLevelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLevelResponse.Marshal(b, m, deterministic)
}
func (m *SetLevelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLevelResponse.Merge(m, src)
}
func (m *SetLevelResponse) XXX_Size() int {
	return xxx_messageInfo_SetLevelResponse.Size(m)
}
func (m *SetLevelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLevelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetLevelResponse proto.InternalMessageInfo

func (m *SetLevelResponse) GetLevel() Level {
	if m != nil {
		return m.Level
	}
	return Level_PANIC
}

func init() {
	proto.RegisterEnum("log.Level", Level_name, Level_value)
	proto.RegisterType((*SetLevelRequest)(nil), "log.SetLevelRequest")
	proto.RegisterType((*SetLevelResponse)(nil), "log.SetLevelResponse")
}

func init() { proto.RegisterFile("log.proto", fileDescriptor_a153da538f858886) }

var fileDescriptor_a153da538f858886 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0xc9, 0x4f, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0xc9, 0x4f, 0x57, 0x32, 0xe6, 0xe2, 0x0f, 0x4e,
	0x2d, 0xf1, 0x49, 0x2d, 0x4b, 0xcd, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x52, 0xe0,
	0x62, 0xcd, 0x01, 0xf1, 0x25, 0x18, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0xb8, 0xf4, 0x40, 0x5a, 0x20,
	0x2a, 0x20, 0x12, 0x4a, 0x26, 0x5c, 0x02, 0x08, 0x4d, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x84,
	0x75, 0x69, 0x05, 0x71, 0xb1, 0x82, 0xf9, 0x42, 0x9c, 0x5c, 0xac, 0x01, 0x8e, 0x7e, 0x9e, 0xce,
	0x02, 0x0c, 0x20, 0xa6, 0x9b, 0x63, 0x88, 0xa3, 0x8f, 0x00, 0x23, 0x88, 0xe9, 0x1a, 0x14, 0xe4,
	0x1f, 0x24, 0xc0, 0x24, 0xc4, 0xc1, 0xc5, 0x12, 0xee, 0x18, 0xe4, 0x27, 0xc0, 0x0c, 0x62, 0x79,
	0xfa, 0xb9, 0xf9, 0x0b, 0xb0, 0x80, 0xa4, 0x5d, 0x5c, 0x9d, 0x42, 0xdd, 0x05, 0x58, 0x41, 0xcc,
	0x90, 0x20, 0x47, 0x67, 0x57, 0x01, 0x36, 0x23, 0x3b, 0x2e, 0x66, 0x9f, 0xfc, 0x74, 0x21, 0x73,
	0x2e, 0x0e, 0x98, 0x83, 0x84, 0x44, 0xc0, 0x36, 0xa3, 0x79, 0x4a, 0x4a, 0x14, 0x4d, 0x14, 0xe2,
	0xea, 0x24, 0x36, 0x70, 0x50, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x65, 0xc6, 0x98,
	0x17, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LogClient is the client API for Log service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogClient interface {
	SetLevel(ctx context.Context, in *SetLevelRequest, opts ...grpc.CallOption) (*SetLevelResponse, error)
}

type logClient struct {
	cc *grpc.ClientConn
}

func NewLogClient(cc *grpc.ClientConn) LogClient {
	return &logClient{cc}
}

func (c *logClient) SetLevel(ctx context.Context, in *SetLevelRequest, opts ...grpc.CallOption) (*SetLevelResponse, error) {
	out := new(SetLevelResponse)
	err := c.cc.Invoke(ctx, "/log.Log/SetLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServer is the server API for Log service.
type LogServer interface {
	SetLevel(context.Context, *SetLevelRequest) (*SetLevelResponse, error)
}

// UnimplementedLogServer can be embedded to have forward compatible implementations.
type UnimplementedLogServer struct {
}

func (*UnimplementedLogServer) SetLevel(ctx context.Context, req *SetLevelRequest) (*SetLevelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLevel not implemented")
}

func RegisterLogServer(s *grpc.Server, srv LogServer) {
	s.RegisterService(&_Log_serviceDesc, srv)
}

func _Log_SetLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).SetLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/log.Log/SetLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).SetLevel(ctx, req.(*SetLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Log_serviceDesc = grpc.ServiceDesc{
	ServiceName: "log.Log",
	HandlerType: (*LogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetLevel",
			Handler:    _Log_SetLevel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log.proto",
}
