// Code generated by protoc-gen-go. DO NOT EDIT.
// source: error.proto

package rest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	code "google.golang.org/genproto/googleapis/rpc/code"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// This corresponds to `google.rpc.Status.code`.
	Code int32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	// This is the enum version for `google.rpc.Status.code`.
	Status code.Code `protobuf:"varint,3,opt,name=status,proto3,enum=google.rpc.Code" json:"status,omitempty"`
	// This corresponds to `google.rpc.Status.message`.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// This corresponds to `google.rpc.Status.details`.
	Details              []*any.Any `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_0579b252106fcf4a, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetStatus() code.Code {
	if m != nil {
		return m.Status
	}
	return code.Code_OK
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetDetails() []*any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "rest.Error")
}

func init() { proto.RegisterFile("error.proto", fileDescriptor_0579b252106fcf4a) }

var fileDescriptor_0579b252106fcf4a = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0x41, 0x6a, 0x84, 0x30,
	0x14, 0x86, 0x49, 0x35, 0x4a, 0x23, 0x94, 0x12, 0x2c, 0xa4, 0xae, 0x42, 0x57, 0x59, 0x45, 0xb0,
	0x27, 0x18, 0x86, 0xb9, 0x40, 0x6e, 0x10, 0xf5, 0x8d, 0x0c, 0x38, 0x46, 0x92, 0xb8, 0xf0, 0x40,
	0x73, 0xcf, 0xc1, 0xc4, 0xec, 0xde, 0xff, 0xff, 0x1f, 0x1f, 0x8f, 0x54, 0x60, 0xad, 0xb1, 0x72,
	0xb5, 0xc6, 0x1b, 0x9a, 0x5b, 0x70, 0xbe, 0xf9, 0x9d, 0x8c, 0x99, 0x66, 0x68, 0x43, 0xd7, 0x6f,
	0xf7, 0x56, 0x2f, 0x7b, 0x04, 0x9a, 0x9f, 0x73, 0xb2, 0xeb, 0xd0, 0x0e, 0x66, 0x84, 0x58, 0xff,
	0xbd, 0x10, 0xc1, 0xb7, 0xc3, 0x43, 0x6b, 0x82, 0x83, 0x90, 0x21, 0x8e, 0xc4, 0xa7, 0x8a, 0x81,
	0x52, 0x92, 0x1f, 0x34, 0xfb, 0xe0, 0x48, 0x60, 0x15, 0x6e, 0x2a, 0x48, 0xe1, 0xbc, 0xf6, 0x9b,
	0x63, 0x19, 0x47, 0xe2, 0xab, 0xfb, 0x96, 0xd1, 0x2d, 0xed, 0x3a, 0xc8, 0xab, 0x19, 0x41, 0x9d,
	0x3b, 0x65, 0xa4, 0x7c, 0x82, 0x73, 0x7a, 0x02, 0x96, 0x07, 0x6b, 0x8a, 0x54, 0x92, 0x72, 0x04,
	0xaf, 0x1f, 0xb3, 0x63, 0x98, 0x67, 0xa2, 0xea, 0xea, 0x24, 0x49, 0xbf, 0xcb, 0xcb, 0xb2, 0xab,
	0x04, 0xf5, 0x45, 0xa8, 0xff, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xd8, 0x42, 0x8c, 0xf5,
	0x00, 0x00, 0x00,
}
